#!/usr/bin/env perl
use warnings;
use strict;

sub usage {
	print STDERR "javadoc-find <class or function>\n";
	print STDERR "JAVADOCS environment variable must be defined\n";
	exit 1;
}

usage() if not defined $ENV{JAVADOCS};
usage() if not defined $ARGV[0];

my @path = split /\./, $ARGV[0];

my $prelast = $path[$#path-1];
my $last = $path[$#path];

my $theclass = "";
my $themeth = undef;

#print "<$prelast>.<$last>\n";

if (not defined $prelast) {
	$theclass = $last;
} else {
	if (lc(substr($last, 0, 1)) eq substr($last, 0, 1)) {
		$theclass = $prelast;
		$themeth = $last;
	} else {
		$theclass = $last;
	}
}

for my $dir (split /:/, $ENV{JAVADOCS}) {
	my @findout = grep { !/class-use/ } split /\n/, `find $dir -name '$theclass.html'`;
	if (@findout > 0) {
		print $findout[0]."\n";
		last;
	}
}
